### ISSUE TITLE
Backspace forces cursor to end of file

### ISSUE THREAD

**Issue by mtlynch** [nalgeon/codapi-js#25] opened 2024-04-21 00:14 UTC
I'm noticing strange behavior on the codapi playground site that I can't reproduce if I run a snippet locally.

https://codapi.org/javascript/

### Repro steps

Enter the following code:

```javascript
const greet = (name) => {
    console.log(5);
}

greet("World");
```

Place the cursor after the `5` and hit the Backspace key on your keyboard.

### Expected

Deletes `5` and cursor remains between parentheses.

### Actual

Deletes `5` and cursor jumps to the end of the file.

I did it with an on-screen keyboard just for demo, but it happens with a physical keyboard as well.

https://github.com/nalgeon/codapi-js/assets/7783288/8ebd0ac9-3841-4baf-a06e-1da468626c89

### Environment

Windows 10 + Firefox 125

**Comment by nalgeon** [comment] 2024-04-21 04:40
Looks really weird 😅 I'm pretty sure it's not related to Codapi itself, but to CodeJar — the editor the playground uses. The bug is reproduced with your steps in Firefox on the CodeJar's [main page](https://medv.io/codejar/). I'll report it to the maintainer. Thank you!

**Comment by nalgeon** [comment] 2024-04-22 06:35
I'm closing this issue, because it is not related to the Codapi widget (it does not use CodeJar), and it is only reproduced on the Codapi website (it does use CodeJar). So the Codapi widget users are not affected in any way.

**Closed by nalgeon** 2024-04-22 06:35 UTC
